<?php
include "../auth.php";
include "../components/helpers.php";
include "../secure/db.php";
include "../components/modal-dialogs.php";
include "../components/notification_js.php";

$role = $USER['role'] ?? '';
$isAdminRole = isAdmin($role);
$isReceptionistRole = hasRole($role, 'receptionist');

if (!$isAdminRole && !$isReceptionistRole) {
    die("Access denied!");
}

$billingStatuses = [
    'paid'      => 'Paid',
    'unpaid'    => 'Unpaid',
    'pending'   => 'Pending',
    'cancelled' => 'Cancelled'
];

$paymentMethods = [
    'cash'          => 'Cash',
    'card'          => 'Card / POS',
    'upi'           => 'UPI',
    'bank_transfer' => 'Bank Transfer',
    'other'         => 'Other'
];

$errors = [];
$success = false;
$createdBillId = null;

// Get next bill ID preview (for display only, actual ID is auto-generated by database)
function getNextBillIdPreview(mysqli $conn, int $patientId): string {
    // Get the last bill_id for this patient
    $stmt = mysqli_prepare($conn, "SELECT MAX(bill_id) as max_id FROM billings WHERE patient_id = ?");
    if ($stmt) {
        mysqli_stmt_bind_param($stmt, 'i', $patientId);
        mysqli_stmt_execute($stmt);
        $result = mysqli_stmt_get_result($stmt);
        $row = mysqli_fetch_assoc($result);
        mysqli_stmt_close($stmt);
        
        if ($row && $row['max_id']) {
            return 'Next: ' . ((int)$row['max_id'] + 1);
        }
        // If no bills exist for this patient, show patient-linked preview
        return 'Will be auto-generated (linked to Patient ID: ' . $patientId . ')';
    }
    return 'Auto-generated after save';
}

$bill_id          = '';
$bill_date        = date('Y-m-d');
$patient_id       = '';
$patient_name     = '';
$consultant_id    = '';
$consultant_name  = '';
$total_amount     = '';
$status           = 'unpaid';
$method           = 'cash';
$notes            = '';

// Auto-populate patient details if patient_id is provided in URL
if (isset($_GET['patient_id']) && is_numeric($_GET['patient_id'])) {
    $prefill_patient_id = (int)$_GET['patient_id'];
    // fetch age and gender as well for prefill
    $stmt = mysqli_prepare($conn, "SELECT id, name, COALESCE(age, '') AS age, COALESCE(gender, '') AS gender FROM patients WHERE id = ?");
    if ($stmt) {
        mysqli_stmt_bind_param($stmt, 'i', $prefill_patient_id);
        mysqli_stmt_execute($stmt);
        $result = mysqli_stmt_get_result($stmt);
        $prefill_patient = mysqli_fetch_assoc($result);
        mysqli_stmt_close($stmt);
        
        if ($prefill_patient) {
            $patient_id = $prefill_patient['id'];
            $patient_name = $prefill_patient['name'];
            // expose additional fields to the page
            $patient = $prefill_patient;
        }
    }
}

function fetchConsultants(mysqli $conn): array {
    $list = [];
    // Fetch consultants with user_id from users table
    $res = @mysqli_query($conn, "SELECT c.id as consultant_table_id, u.id as user_id, u.name, c.user_id 
                                   FROM consultants c 
                                   JOIN users u ON u.id = c.user_id 
                                   WHERE c.status = 'active' 
                                   ORDER BY u.name ASC");
    if ($res) {
        while ($row = mysqli_fetch_assoc($res)) {
            $list[] = $row;
        }
    }
    return $list;
}

function fetchRecentPatients(mysqli $conn, int $limit = 100): array {
    $list = [];
    $res = @mysqli_query($conn, "SELECT id, name FROM patients ORDER BY id DESC LIMIT " . (int)$limit);
    if ($res) {
        while ($row = mysqli_fetch_assoc($res)) {
            $list[] = $row;
        }
    }
    return $list;
}

function fetchBillingItems(mysqli $conn): array {
    $list = [];
    $res = @mysqli_query($conn, "SELECT id, item_name, price FROM billing_items ORDER BY item_name ASC");
    if ($res) {
        while ($row = mysqli_fetch_assoc($res)) {
            $list[] = $row;
        }
    }
    return $list;
}

$consultants    = fetchConsultants($conn);
$recentPatients = fetchRecentPatients($conn);
$billingItems   = fetchBillingItems($conn);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $bill_date        = trim($_POST['bill_date'] ?? '');
    $patient_id       = trim($_POST['patient_id'] ?? '');
    $patient_name     = trim($_POST['patient_name'] ?? '');
    $consultant_id    = trim($_POST['consultant_id'] ?? '');
    $consultant_name  = trim($_POST['consultant_name'] ?? '');
    $total_amount     = trim($_POST['total_amount'] ?? '');
    $billing_item_id  = trim($_POST['billing_item_id'] ?? '');
    $status           = trim($_POST['status'] ?? 'unpaid');
    $method           = trim($_POST['method'] ?? 'cash');
    $notes            = trim($_POST['notes'] ?? '');
    $updated_by       = trim($_POST['updated_by'] ?? '');
    
    $patient_id_val = ($patient_id === '') ? null : (int)$patient_id;

    if ($bill_date === '' || !DateTime::createFromFormat('Y-m-d', $bill_date)) {
        $errors[] = "Bill date is required.";
    }

    if ($patient_id_val === null) {
        $errors[] = "Patient is required.";
    }

    $consultant_id_val = ($consultant_id === '') ? null : (int)$consultant_id;

    $total_amount_val = is_numeric($total_amount) ? (float)$total_amount : null;

    if ($total_amount_val === null || $total_amount_val < 0) {
        $errors[] = "Total amount must be a non-negative number.";
    }

    if (!isset($billingStatuses[$status])) {
        $status = 'unpaid';
    }

    if (!isset($paymentMethods[$method])) {
        $method = 'cash';
    }

    if ($patient_id_val && $patient_name === '') {
        $stmt = mysqli_prepare($conn, "SELECT name FROM patients WHERE id = ?");
        if ($stmt) {
            mysqli_stmt_bind_param($stmt, 'i', $patient_id_val);
            mysqli_stmt_execute($stmt);
            mysqli_stmt_bind_result($stmt, $dbPatientName);
            if (mysqli_stmt_fetch($stmt)) {
                $patient_name = $dbPatientName;
            }
            mysqli_stmt_close($stmt);
        }
    }

    if ($consultant_id_val && $consultant_name === '') {
        $stmt = mysqli_prepare($conn, "SELECT u.name 
                                       FROM consultants c 
                                       JOIN users u ON u.id = c.user_id 
                                       WHERE c.id = ?");
        if ($stmt) {
            mysqli_stmt_bind_param($stmt, 'i', $consultant_id_val);
            mysqli_stmt_execute($stmt);
            mysqli_stmt_bind_result($stmt, $dbConsultantName);
            if (mysqli_stmt_fetch($stmt)) {
                $consultant_name = $dbConsultantName;
            }
            mysqli_stmt_close($stmt);
        }
    }

    if ($patient_name === '') {
        $errors[] = "Patient name is required.";
    }

    if ($consultant_name === '') {
        $errors[] = "Consultant name is required.";
    }

    if (empty($errors)) {
        // Ensure `items_json` column exists in `billings` table (safe check)
        $colCheck = mysqli_query($conn, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'billings' AND COLUMN_NAME = 'items_json'");
        if ($colCheck && mysqli_num_rows($colCheck) === 0) {
            @mysqli_query($conn, "ALTER TABLE billings ADD COLUMN items_json TEXT NULL AFTER notes");
        }

        // If a billing item was selected, fetch its details and prepare items_json (do NOT prepend into notes)
        $items_json = null;
        if ($billing_item_id !== '') {
            $biStmt = $conn->prepare("SELECT id, item_name, price FROM billing_items WHERE id = ? LIMIT 1");
            if ($biStmt) {
                $biStmt->bind_param('i', $billing_item_id);
                $biStmt->execute();
                $biRes = $biStmt->get_result();
                if ($biRow = $biRes->fetch_assoc()) {
                    $line = [
                        'billing_item_id' => (int)$biRow['id'],
                        'description' => $biRow['item_name'],
                        'quantity' => 1,
                        'rate' => (float)$biRow['price'],
                        'amount' => (float)$biRow['price']
                    ];
                    $itemsArr = [$line];
                    $items_json = json_encode($itemsArr);
                }
                $biStmt->close();
            }
        }

        // Set updated_by from POST data (or fallback to current user id if not provided)
        // Only set if it's a valid positive integer that exists in users table
        $updated_by_val = null;
        if ($updated_by !== '' && (int)$updated_by > 0) {
            $updated_by_val = (int)$updated_by;
        } elseif (isset($USER['id']) && (int)$USER['id'] > 0) {
            $updated_by_val = (int)$USER['id'];
        }

        $sql = "INSERT INTO billings (
                    bill_date,
                    patient_id,
                    patient_name,
                    consultant_id,
                    consultant_name,
                    total_amount,
                    status,
                    method,
                    notes,
                    items_json,
                    updated_by,
                    created_at,
                    updated_at
                ) VALUES (
                    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW()
                )";

        $stmt = mysqli_prepare($conn, $sql);
        if ($stmt) {
            mysqli_stmt_bind_param(
                $stmt,
                'sisisdssssi',
                $bill_date,
                $patient_id_val,
                $patient_name,
                $consultant_id_val,
                $consultant_name,
                $total_amount_val,
                $status,
                $method,
                $notes,
                $items_json,
                $updated_by_val
            );

            if (mysqli_stmt_execute($stmt)) {
                $success = true;
                $createdBillId = mysqli_insert_id($conn);
                $bill_id = $createdBillId;
                // Reset form after successful save
                $bill_date = date('Y-m-d');
                $patient_id = $patient_name = '';
                $consultant_id = $consultant_name = '';
                $total_amount = '';
                $status = 'unpaid';
                $method = 'cash';
                $notes = '';
            } else {
                $errors[] = "Unable to create bill. " . mysqli_error($conn);
            }
            mysqli_stmt_close($stmt);
        } else {
            $errors[] = "Failed to prepare statement: " . mysqli_error($conn);
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Bill</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../css/common.css">
    <link rel="stylesheet" href="../css/patient-pages.css">
</head>
<body class="patient-surface">
<div class="patient-shell">
    <header class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div>
            <h1 class="page-title mb-0">Create Bill</h1>
            <p class="sub-text mb-0">Create a new bill for patient visit</p>
        </div>
        <?php if ($createdBillId): ?>
            <div class="badge bg-success fs-6 align-self-center">
                Bill #<?= htmlspecialchars($createdBillId) ?> created
            </div>
        <?php endif; ?>
    </header>

    <div class="patient-form-card glass-panel">
        <form method="post" class="row g-3" novalidate id="billForm">
            <input type="hidden" name="updated_by" value="<?= (int)($USER['id'] ?? 0) ?>">
            <div class="col-md-4">
                <label class="form-label">Bill ID</label>
                <input type="text" id="billIdDisplay" class="form-control" value="<?= $createdBillId ? htmlspecialchars($createdBillId) : (($patient_id && is_numeric($patient_id)) ? getNextBillIdPreview($conn, (int)$patient_id) : 'Auto-generated after save') ?>" readonly style="background-color: #f8f9fa;">
            </div>

            <div class="col-md-4">
                <label class="form-label">Bill Date <span class="text-danger">*</span></label>
                <input type="date" name="bill_date" class="form-control" value="<?= htmlspecialchars($bill_date) ?>" required>
            </div>

            <div class="col-md-4">
                <label class="form-label">Patient Name <span class="text-danger">*</span></label>
                <input type="text" id="patientNameInput" class="form-control" autocomplete="off" placeholder="Type patient name..." value="<?= htmlspecialchars($patient_name) ?>" required>
                <div id="patientNameDropdown" class="autocomplete-dropdown"></div>
            </div>

            <div class="col-md-2">
                <label class="form-label">Patient ID</label>
                <input type="text" id="patientIdDisplay" class="form-control" placeholder="Auto-fill" readonly style="background-color: #f8f9fa;">
                <input type="hidden" name="patient_id" id="patientIdHidden"  value="<?= htmlspecialchars($patient_id) ?>">
            </div>

            <div class="col-md-2">
                <label class="form-label">Age</label>
                <input type="text" id="patientAgeDisplay" class="form-control" placeholder="Auto-fill" readonly style="background-color: #f8f9fa;">          
            </div>

            <div class="col-md-2">
                <label class="form-label">Gender</label>
                <input type="text" id="patientGenderDisplay" class="form-control" placeholder="Auto-fill" readonly style="background-color: #f8f9fa;">
            </div>

            
            <div class="col-md-2">
                <label class="form-label">Consultant ID</label>
                <input type="text" id="consultantIdDisplay" class="form-control" placeholder="Auto-fill" readonly style="background-color: #f8f9fa;">
                <input type="hidden" name="consultant_id" id="consultantIdHidden" value="<?= htmlspecialchars($consultant_id) ?>">
            </div>

            <div class="col-md-4">
                <label class="form-label">Consultant Name <span class="text-danger">*</span></label>
                <input type="text" id="consultantNameInput" class="form-control" autocomplete="off" placeholder="Type consultant name..." value="<?= htmlspecialchars($consultant_name) ?>" required>
                <div id="consultantNameDropdown" class="autocomplete-dropdown"></div>
            </div>


            <div class="col-md-6">
                <label class="form-label">Billing Item</label>
                <select name="billing_item_id" id="billingItemSelect" class="form-select" onchange="populatePrice()">
                    <option value="">-- Select an item --</option>
                    <?php foreach ($billingItems as $item): ?>
                        <option value="<?= (int)$item['id'] ?>" data-price="<?= htmlspecialchars($item['price']) ?>">
                            <?= htmlspecialchars($item['item_name']) ?> (₹<?= number_format($item['price'], 2) ?>)
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-6">
                <label class="form-label">Total Amount (₹) <span class="text-danger">*</span></label>
                <input type="number" step="0.01" min="0" name="total_amount" id="totalAmountField" class="form-control" value="<?= htmlspecialchars($total_amount) ?>" required>
            </div>

            <div class="col-md-4">
                <label class="form-label">Status</label>
                <select name="status" class="form-select">
                    <?php foreach ($billingStatuses as $value => $label): ?>
                        <option value="<?= $value ?>" <?= $status === $value ? 'selected' : '' ?>>
                            <?= htmlspecialchars($label) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-4">
                <label class="form-label">Payment Method</label>
                <select name="method" class="form-select">
                    <?php foreach ($paymentMethods as $value => $label): ?>
                        <option value="<?= $value ?>" <?= $method === $value ? 'selected' : '' ?>>
                            <?= htmlspecialchars($label) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-4">
                <label class="form-label">Notes (Optional)</label>
                <textarea name="notes" class="form-control" rows="1" placeholder="Additional notes..."><?= htmlspecialchars(getCleanNotes($notes)) ?></textarea>
            </div>

            <div class="col-12 mt-5">
                <div class="d-flex justify-content-end gap-2">
                    <button type="button" class="btn btn-outline-secondary" onclick="printBill()">
                        <i class="bi bi-printer"></i> Print
                    </button>
                    <button type="submit" class="btn btn-add">
                        <i class="bi bi-save"></i> Save Bill
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<style>
.autocomplete-dropdown {
    position: absolute;
    z-index: 1000;
    background: #fff;
    border: 1px solid #ccc;
    border-radius: 0 0 6px 6px;
    max-height: 100px;
    overflow-y: auto;
    width: 30%;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    display: none;
}
.autocomplete-dropdown .dropdown-item {
    cursor: pointer;
    padding: 8px 12px;
}
.autocomplete-dropdown .dropdown-item:hover {
    background: #f1f1f1;
}
</style>
<script>
// --- Patient Name Autocomplete ---
const patientInput = document.getElementById('patientNameInput');
const patientDropdown = document.getElementById('patientNameDropdown');
const patientIdHidden = document.getElementById('patientIdHidden');
let patientTimeout = null;
patientInput.addEventListener('input', function() {
    const val = this.value.trim();
    patientIdHidden.value = '';
    if (val.length < 2) {
        patientDropdown.style.display = 'none';
        return;
    }
    clearTimeout(patientTimeout);
    patientTimeout = setTimeout(() => {
        fetch('patient_search.php?q=' + encodeURIComponent(val))
            .then(r => r.json())
            .then(obj => {
                const arr = Array.isArray(obj) ? obj : (obj.items || []);
                if (!Array.isArray(arr) || arr.length === 0) {
                    patientDropdown.style.display = 'none';
                    return;
                }
                patientDropdown.innerHTML = arr.map(p => `
                    <div class="dropdown-item" data-id="${p.id}" data-name="${p.name}" data-age="${p.age}" data-gender="${p.gender}">
                        ${p.name} ${p.age ? (' | ' + p.age) : ''} ${p.gender ? (' | ' + p.gender) : ''}
                    </div>
                `).join('');
                patientDropdown.style.display = 'block';
            }).catch(() => { patientDropdown.style.display = 'none'; });
    }, 200);
});
patientDropdown.addEventListener('mousedown', function(e) {
    if (e.target.classList.contains('dropdown-item')) {
        patientInput.value = e.target.dataset.name;
        patientIdHidden.value = e.target.dataset.id;
        // populate readonly ID display
        const patientIdDisplay = document.getElementById('patientIdDisplay');
        if (patientIdDisplay) patientIdDisplay.value = e.target.dataset.id;
        // populate age/gender displays
        const patientAgeDisplay = document.getElementById('patientAgeDisplay');
        const patientGenderDisplay = document.getElementById('patientGenderDisplay');
        if (patientAgeDisplay) patientAgeDisplay.value = e.target.dataset.age || '';
        if (patientGenderDisplay) patientGenderDisplay.value = e.target.dataset.gender || '';
        // update bill id preview
        const billIdDisplay = document.getElementById('billIdDisplay');
        if (billIdDisplay && e.target.dataset.id) {
            billIdDisplay.value = 'Will be auto-generated (Patient ID: ' + e.target.dataset.id + ')';
        }
        patientDropdown.style.display = 'none';
    }
});
document.addEventListener('click', function(e) {
    if (!patientDropdown.contains(e.target) && e.target !== patientInput) {
        patientDropdown.style.display = 'none';
    }
});

// --- Consultant Username Autocomplete ---
const consultantInput = document.getElementById('consultantNameInput');
const consultantDropdown = document.getElementById('consultantNameDropdown');
const consultantIdHidden = document.getElementById('consultantIdHidden');
let consultantTimeout = null;
consultantInput.addEventListener('input', function() {
    const val = this.value.trim();
    consultantIdHidden.value = '';
    if (val.length < 2) {
        consultantDropdown.style.display = 'none';
        return;
    }
    clearTimeout(consultantTimeout);
    consultantTimeout = setTimeout(() => {
        fetch('consultant_search.php?q=' + encodeURIComponent(val))
            .then(r => r.json())
            .then(arr => {
                if (!Array.isArray(arr) || arr.length === 0) {
                    consultantDropdown.style.display = 'none';
                    return;
                }
                consultantDropdown.innerHTML = arr.map(c => `<div class="dropdown-item" data-id="${c.id}" data-name="${c.name}">${c.name}</div>`).join('');
                consultantDropdown.style.display = 'block';
            });
    }, 200);
});
consultantDropdown.addEventListener('mousedown', function(e) {
    if (e.target.classList.contains('dropdown-item')) {
        consultantInput.value = e.target.dataset.name;
        consultantIdHidden.value = e.target.dataset.id;
        const consultantIdDisplay = document.getElementById('consultantIdDisplay');
        if (consultantIdDisplay) consultantIdDisplay.value = e.target.dataset.id;
        consultantDropdown.style.display = 'none';
    }
});
document.addEventListener('click', function(e) {
    if (!consultantDropdown.contains(e.target) && e.target !== consultantInput) {
        consultantDropdown.style.display = 'none';
    }
});
const createdBillId = <?= json_encode($createdBillId) ?>;

function populatePrice() {
    const select = document.getElementById('billingItemSelect');
    const option = select.options[select.selectedIndex];
    const price = option?.getAttribute('data-price');
    if (price) {
        document.getElementById('totalAmountField').value = price;
    }
}

function updatePatientInfo() {
    const sel = document.getElementById('patientSelect');
    const hidden = document.getElementById('patientNameHidden');
    const display = document.getElementById('patientNameDisplay');
    if (!sel) return;
    const opt = sel.options[sel.selectedIndex];
    const patientName = opt && opt.dataset.name ? opt.dataset.name : '';
    if (hidden) hidden.value = patientName;
    if (display) display.value = patientName;
}

function updateConsultantInfo() {
    const sel = document.getElementById('consultantSelect');
    const hidden = document.getElementById('consultantNameHidden');
    const display = document.getElementById('consultantNameDisplay');
    if (!sel) return;
    const opt = sel.options[sel.selectedIndex];
    const consultantName = opt && opt.dataset.name ? opt.dataset.name : '';
    if (hidden) hidden.value = consultantName;
    if (display) display.value = consultantName;
}

function printBill() {
    if (createdBillId && Number(createdBillId) > 0) {
        window.open(`print_bill.php?id=${createdBillId}&autoprint=1`, '_blank');
    } else {
        if (typeof showErrorModal === 'function') {
            showErrorModal('Please save the bill first.', 'Print Bill');
        } else {
            alert('Please save the bill first.');
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    // Initialize fields if preselected
    updatePatientInfo();
    updateConsultantInfo();
    
    // If patient_id is pre-filled from URL, make sure patient name is displayed
    <?php if ($patient_id && $patient_name): ?>
    const patientNameInput = document.getElementById('patientNameInput');
    const patientIdHidden = document.getElementById('patientIdHidden');
    if (patientNameInput) {
        patientNameInput.value = <?= json_encode($patient_name) ?>;
    }
    if (patientIdHidden) {
        patientIdHidden.value = <?= json_encode($patient_id) ?>;
    }
    const patientAgeDisplay = document.getElementById('patientAgeDisplay');
    const patientGenderDisplay = document.getElementById('patientGenderDisplay');
    if (patientAgeDisplay) patientAgeDisplay.value = <?= json_encode($patient['age'] ?? '') ?>;
    if (patientGenderDisplay) patientGenderDisplay.value = <?= json_encode($patient['gender'] ?? '') ?>;
    <?php endif; ?>
    
    // Update bill ID preview when patient is selected
    const patientSelect = document.getElementById('patientSelect');
    if (patientSelect) {
        patientSelect.addEventListener('change', function() {
            const patientId = this.value;
            const billIdDisplay = document.getElementById('billIdDisplay');
            if (billIdDisplay && patientId) {
                // Fetch preview via AJAX or show placeholder
                billIdDisplay.value = 'Will be auto-generated (Patient ID: ' + patientId + ')';
            } else if (billIdDisplay) {
                billIdDisplay.value = 'Auto-generated after save';
            }
    });

    const form = document.getElementById('billForm');
    if (form) {
        form.addEventListener('submit', function (e) {
            if (form.dataset.confirmed === '1') {
                form.dataset.confirmed = '';
                return;
            }
            e.preventDefault();
            const msg = 'Are you sure you want to save this bill?';
            if (typeof showConfirmModal === 'function') {
                showConfirmModal(msg, function () {
                    form.dataset.confirmed = '1';
                    form.submit();
                });
            } else if (confirm(msg)) {
                form.submit();
            }
        });
    }
    }
    
    // Update bill ID display if created
    <?php if ($createdBillId): ?>
    const billIdDisplay = document.getElementById('billIdDisplay');
    if (billIdDisplay) {
        billIdDisplay.value = <?= (int)$createdBillId ?>;
    }
    <?php endif; ?>
});
</script>
<?php if ($success): ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
    if (typeof showSuccessModal === 'function') {
        showSuccessModal('Bill has been saved successfully.', 'Bill Saved');
    }
});
</script>
<?php endif; ?>
<?php if (!empty($errors)): ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
    if (typeof showErrorModal === 'function') {
        showErrorModal(<?= json_encode(implode("\n", $errors)) ?>, 'Unable to save bill');
    }
});
</script>
<?php endif; ?>
</body>
</html>

